// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysPost = "sys_posts"

// SysPost mapped from table <sys_posts>
type SysPost struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键id" json:"id"`       // 主键id
	PostName  string         `gorm:"column:post_name;type:varchar(128);not null;comment:岗位名称" json:"post_name"`        // 岗位名称
	PostCode  string         `gorm:"column:post_code;type:varchar(128);not null;comment:岗位代码" json:"post_code"`        // 岗位代码
	Sort      int32          `gorm:"column:sort;type:int;not null;comment:岗位排序" json:"sort"`                           // 岗位排序
	Status    int32          `gorm:"column:status;type:tinyint;not null;default:1;comment:状态 1=正常 2=冻结" json:"status"` // 状态 1=正常 2=冻结
	Remark    string         `gorm:"column:remark;type:varchar(255);not null;comment:描述" json:"remark"`                // 描述
	CreateBy  string         `gorm:"column:create_by;type:varchar(64);not null;comment:创建人" json:"create_by"`          // 创建人
	UpdateBy  string         `gorm:"column:update_by;type:varchar(64);not null;comment:修改人" json:"update_by"`          // 修改人
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                   // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                   // 删除时间
}

// TableName SysPost's table name
func (*SysPost) TableName() string {
	return TableNameSysPost
}
